### PR TITLE
Add route-registrar for friendlier PCF urls

### PR DESCRIPTION
**Pull request by rmeharg**

### CODE REVIEW

**Comment by mkuratczyk** [comment]
Thanks Ryan!

**Comment by DenverOps** [comment]
@mkuratczyk should I put in an issue for the new Route Registrar?  I believe it's broke per our last chat.

**Comment by mkuratczyk** [comment]
I've just pushed https://github.com/pivotal-cf/pcf-prometheus-pipeline/commit/ba4b798d79c2eaa999bbe689e98bb3cf2d155b5c to disable it by default.

@RMeharg there are a few problems with this:
1. It fails when deploying to an external BOSH director
1. It's explicit about release versions with but doesn't actually upload these versions
1. Even if the releases are there, sometimes they are only available as compiled for xenial stemcells so it still fails trying to deploy to trusty (we can change the default to xenial soon I guess)

**Comment by rmeharg** [comment]
@mkuratczyk good points

1. Yes, it has to be on the same director as CF until we have cross-director links (https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/cross-director-links.png)
2. I'm not sure I understand, it follows the same format as prometheus-boshrelease, we could use github-release resource if it wasn't optional
3. All releases should be switching to xenial as soon as possible :)

I am fine with leaving this as an optional operations file.

**Pull request merged**
